auto_add = false
format = 'UseEmoji'
signed = false
scope = false
update_url = 'https://gitmoji.dev/api/gitmojis'

[[gitmojis]]
emoji = 'âœ¨'
code = ':sparkles:'
name = 'sparkles'
description = 'Introduce new features.'

[[gitmojis]]
emoji = 'ğŸ›'
code = ':bug:'
name = 'bug'
description = 'Fix a bug.'

[[gitmojis]]
emoji = 'ğŸ¨'
code = ':art:'
name = 'art'
description = 'Improve structure / format of the code.'

[[gitmojis]]
emoji = 'âš¡ï¸'
code = ':zap:'
name = 'zap'
description = 'Improve performance.'


[[gitmojis]]
emoji = 'ğŸš‘ï¸'
code = ':ambulance:'
name = 'ambulance'
description = 'Critical hotfix.'

[[gitmojis]]
emoji = 'ğŸ“'
code = ':memo:'
name = 'memo'
description = 'Add or update documentation.'

[[gitmojis]]
emoji = 'ğŸš€'
code = ':rocket:'
name = 'rocket'
description = 'Deploy stuff.'

[[gitmojis]]
emoji = 'ğŸ‰'
code = ':tada:'
name = 'tada'
description = 'Begin a project.'

[[gitmojis]]
emoji = 'âœ…'
code = ':white_check_mark:'
name = 'white-check-mark'
description = 'Add, update, or pass tests.'

[[gitmojis]]
emoji = 'ğŸ”’ï¸'
code = ':lock:'
name = 'lock'
description = 'Fix security issues.'

[[gitmojis]]
emoji = 'ğŸ”–'
code = ':bookmark:'
name = 'bookmark'
description = 'Release / Version tags.'

[[gitmojis]]
emoji = 'ğŸš¨'
code = ':rotating_light:'
name = 'rotating-light'
description = 'Fix compiler / linter warnings.'

[[gitmojis]]
emoji = 'ğŸš§'
code = ':construction:'
name = 'construction'
description = 'Work in progress.'

[[gitmojis]]
emoji = 'ğŸ’š'
code = ':green_heart:'
name = 'green-heart'
description = 'Fix CI Build.'

[[gitmojis]]
emoji = 'â¬‡ï¸'
code = ':arrow_down:'
name = 'arrow-down'
description = 'Downgrade dependencies.'

[[gitmojis]]
emoji = 'â¬†ï¸'
code = ':arrow_up:'
name = 'arrow-up'
description = 'Upgrade dependencies.'

[[gitmojis]]
emoji = 'ğŸ“Œ'
code = ':pushpin:'
name = 'pushpin'
description = 'Pin dependencies to specific versions.'

[[gitmojis]]
emoji = 'ğŸ‘·'
code = ':construction_worker:'
name = 'construction-worker'
description = 'Add or update CI build system.'

[[gitmojis]]
emoji = 'â™»ï¸'
code = ':recycle:'
name = 'recycle'
description = 'Refactor code.'

[[gitmojis]]
emoji = 'â•'
code = ':heavy_plus_sign:'
name = 'heavy-plus-sign'
description = 'Add a dependency.'

[[gitmojis]]
emoji = 'â–'
code = ':heavy_minus_sign:'
name = 'heavy-minus-sign'
description = 'Remove a dependency.'

[[gitmojis]]
emoji = 'ğŸ”§'
code = ':wrench:'
name = 'wrench'
description = 'Add or update configuration files.'

[[gitmojis]]
emoji = 'ğŸ”¨'
code = ':hammer:'
name = 'hammer'
description = 'Add or update development scripts.'

[[gitmojis]]
emoji = 'ğŸŒ'
code = ':globe_with_meridians:'
name = 'globe-with-meridians'
description = 'Internationalization and localization.'

[[gitmojis]]
emoji = 'âœï¸'
code = ':pencil2:'
name = 'pencil2'
description = 'Fix typos.'

[[gitmojis]]
emoji = 'ğŸ’©'
code = ':poop:'
name = 'poop'
description = 'Write bad code that needs to be improved.'

[[gitmojis]]
emoji = 'âªï¸'
code = ':rewind:'
name = 'rewind'
description = 'Revert changes.'

[[gitmojis]]
emoji = 'ğŸ”€'
code = ':twisted_rightwards_arrows:'
name = 'twisted-rightwards-arrows'
description = 'Merge branches.'

[[gitmojis]]
emoji = 'ğŸ“¦ï¸'
code = ':package:'
name = 'package'
description = 'Add or update compiled files or packages.'

[[gitmojis]]
emoji = 'ğŸšš'
code = ':truck:'
name = 'truck'
description = 'Move or rename resources (e.g.: files, paths, routes).'

[[gitmojis]]
emoji = 'ğŸ’¥'
code = ':boom:'
name = 'boom'
description = 'Introduce breaking changes.'

[[gitmojis]]
emoji = 'â™¿ï¸'
code = ':wheelchair:'
name = 'wheelchair'
description = 'Improve accessibility.'

[[gitmojis]]
emoji = 'ğŸ’¡'
code = ':bulb:'
name = 'bulb'
description = 'Add or update comments in source code.'

[[gitmojis]]
emoji = 'ğŸ”Š'
code = ':loud_sound:'
name = 'loud-sound'
description = 'Add or update logs.'

[[gitmojis]]
emoji = 'ğŸ”‡'
code = ':mute:'
name = 'mute'
description = 'Remove logs.'

[[gitmojis]]
emoji = 'ğŸ‘¥'
code = ':busts_in_silhouette:'
name = 'busts-in-silhouette'
description = 'Add or update contributor(s).'

[[gitmojis]]
emoji = 'ğŸš¸'
code = ':children_crossing:'
name = 'children-crossing'
description = 'Improve user experience / usability.'

[[gitmojis]]
emoji = 'ğŸ—ï¸'
code = ':building_construction:'
name = 'building-construction'
description = 'Make architectural changes.'

[[gitmojis]]
emoji = 'âš—ï¸'
code = ':alembic:'
name = 'alembic'
description = 'Perform experiments.'

[[gitmojis]]
emoji = 'ğŸš©'
code = ':triangular_flag_on_post:'
name = 'triangular-flag-on-post'
description = 'Add, update, or remove feature flags.'

[[gitmojis]]
emoji = 'ğŸ—‘ï¸'
code = ':wastebasket:'
name = 'wastebasket'
description = 'Deprecate code that needs to be cleaned up.'

[[gitmojis]]
emoji = 'ğŸ©¹'
code = ':adhesive_bandage:'
name = 'adhesive-bandage'
description = 'Simple fix for a non-critical issue.'

[[gitmojis]]
emoji = 'ğŸ§ª'
code = ':test_tube:'
name = 'test-tube'
description = 'Add a failing test.'

[[gitmojis]]
emoji = 'ğŸ©º'
code = ':stethoscope:'
name = 'stethoscope'
description = 'Add or update healthcheck.'

[[gitmojis]]
emoji = 'ğŸ§±'
code = ':bricks:'
name = 'bricks'
description = 'Infrastructure related changes.'

[[gitmojis]]
emoji = 'ğŸ§‘â€ğŸ’»'
code = ':technologist:'
name = 'technologist'
description = 'Improve developer experience'

[[gitmojis]]
emoji = 'ğŸ§µ'
code = ':thread:'
name = 'thread'
description = 'Add or update code related to multithreading or concurrency.'
